[ general ]
haddock_path = '/Users/rodrigo/repos/haddock'
dataset_path = '/Users/rodrigo/repos/haddock-benchmark-tools/example'
python2 = '/usr/bin/python2'
receptor_suffix = '_r_u.pdb'
ligand_suffix = '_l_u.pdb'

# ==============================

[ scenario_1 ]
run_name = 'true-interface'
ambig_tbl = 'ambig.tbl'

[ scenario_2 ]
run_name = 'center-of-mass'
cmrest = true

[ scenario_3 ]
run_name = 'surface-restraints'
surfrest = true

# ==============================
